import http from '@http/http'
export const commodityPage = query => http.GET('./api/commodity/commodityPage', query)
export const commodityPageInOrder = query => http.GET('./api/commodity/commodityPageInOrder', query)
export const updateCommodity = commodity => http.GET('./api/commodity/updateCommodity', commodity)
export const deleteCommodityById = commodity => http.DELETE(`./api/commodity/deleteCommodity/${commodity.id}`, commodity)
export const addCommodity = commodity => http.GET('./api/commodity/createCommodity', commodity)
export const getCommodityById = query => http.GET(`./api/commodity/getCommodity/${query.id}`, query)
export const getBarcodesByComId = id => http.GET('./api/multibarcode/getBarcodes', id)
export const updateBarcodes = barcodes => http.POSTJson('./api/multibarcode/updateBarcodes', barcodes)
export const addBarcodes = (barcodes, query) => http.POSTJson(`./api/multibarcode/addBarcodes/${query.supId}`, barcodes)
export const deleteBarcodes = barcodes => http.POSTJson('./api/multibarcode/deleteBarcodes', barcodes)
export const searchCommodities = query => http.GET('./api/commodity/searchCommodities', query)
export const advanceSearchPage = query => http.POST('./api/commodity/advanceSearch', query)
export const exportCommodities = commodity => http.EXPORT('./api/commodity/exportCommodities', commodity)
export const advanceExport = map => http.EXPORT('./api/commodity/advanceExport', map)
export const exportTemplate = () => http.EXPORT('./api/commodity/exportTemplate')
export const getCombinations = supId => http.GET('./api/commodity/getCombinations', supId)
export const getCommodityByBarcode = commodity => http.GET('./api/commodity/getCommodity', commodity)
export const deleteCombination = commodity => http.POST('./api/commodity/deleteCombination', commodity)
export const searchCombinations = commodity => http.GET('./api/commodity/searchCombinations', commodity)
export const isCombined = commodity => http.GET('./api/commodity/isCombined', commodity)
export const searchWarning = query => http.POST('./api/commodity/searchWarning', query)
